# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: BootstrapTutorialHub.com
# email: contact@bootstraptutorialhub.com
description: > # this means to ignore newlines until "baseurl:"
  Step by step Bootstrap tutorials for beginners and advance users to create powerful responsive and mobile friendly websites.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bootstraptutorialhub.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: TahirTaous
github_username:  TahirTaous

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock

highlighter: rouge
permalink: /:title

## if you want to use Pagination on your jekyll blog, install paginate plugin.
# http://jekyllrb.com/docs/pagination/
# 1. To enable pagination on jekyll website, RENAME index.md to indexold.md 
# 2. copy home.html to route folder of local site from _layouts folder of MINIMA THEME.
# 3. rename home.html to index.html
# 4. replace this line {% for post in site.posts %} WITH {% for post in paginator.posts %}
# 5. copy <!-- Pagination links --> code from http://jekyllrb.com/docs/pagination/ and paste below loop 
# 6. Add gem "jekyll-paginate" in gemfile
# 7. Add - jekyll-paginate in config file
# 8. use following code to chnage nuber of post to display on each paginated page
paginate: 10
paginate_path: /page:num



site.google_analytics: UA-87329913-1
google_site_verification: Tm05_J21gpm1FMrZ2aq7cG9VjUXeph0c5le5FcYflJ0